# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'control.ui'
##
## Created by: Qt User Interface Compiler version 6.9.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QDoubleSpinBox, QGroupBox,
    QLabel, QPushButton, QSizePolicy, QWidget)

class Ui_super_student_clap(object):
    def setupUi(self, super_student_clap):
        if not super_student_clap.objectName():
            super_student_clap.setObjectName(u"super_student_clap")
        super_student_clap.resize(1820, 980)
        self.groupBox = QGroupBox(super_student_clap)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(1300, 10, 231, 211))
        self.label = QLabel(self.groupBox)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 40, 61, 21))
        font = QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label_2 = QLabel(self.groupBox)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 70, 71, 41))
        self.label_2.setFont(font)
        self.label_2.setScaledContents(False)
        self.label_2.setWordWrap(False)
        self.label_2.setOpenExternalLinks(False)
        self.label_3 = QLabel(self.groupBox)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 120, 71, 31))
        self.label_3.setFont(font)
        self.dakaichuankou = QPushButton(self.groupBox)
        self.dakaichuankou.setObjectName(u"dakaichuankou")
        self.dakaichuankou.setGeometry(QRect(20, 170, 91, 31))
        self.dakaichuankou.setFont(font)
        self.guanbichuankou = QPushButton(self.groupBox)
        self.guanbichuankou.setObjectName(u"guanbichuankou")
        self.guanbichuankou.setGeometry(QRect(130, 170, 91, 31))
        self.guanbichuankou.setFont(font)
        self.botelv = QComboBox(self.groupBox)
        self.botelv.addItem("")
        self.botelv.addItem("")
        self.botelv.addItem("")
        self.botelv.addItem("")
        self.botelv.addItem("")
        self.botelv.addItem("")
        self.botelv.addItem("")
        self.botelv.addItem("")
        self.botelv.addItem("")
        self.botelv.setObjectName(u"botelv")
        self.botelv.setGeometry(QRect(90, 80, 111, 31))
        self.chuankou = QComboBox(self.groupBox)
        self.chuankou.addItem("")
        self.chuankou.setObjectName(u"chuankou")
        self.chuankou.setGeometry(QRect(90, 40, 111, 31))
        self.dianjishu = QComboBox(self.groupBox)
        self.dianjishu.addItem("")
        self.dianjishu.addItem("")
        self.dianjishu.addItem("")
        self.dianjishu.addItem("")
        self.dianjishu.addItem("")
        self.dianjishu.addItem("")
        self.dianjishu.setObjectName(u"dianjishu")
        self.dianjishu.setGeometry(QRect(90, 120, 111, 31))
        self.groupBox_2 = QGroupBox(super_student_clap)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(10, 0, 161, 181))
        font1 = QFont()
        font1.setPointSize(11)
        self.groupBox_2.setFont(font1)
        self.label_7 = QLabel(self.groupBox_2)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 30, 51, 21))
        self.sudu1 = QDoubleSpinBox(self.groupBox_2)
        self.sudu1.setObjectName(u"sudu1")
        self.sudu1.setGeometry(QRect(70, 60, 81, 21))
        self.sudu1.setMaximum(10000.000000000000000)
        self.label_8 = QLabel(self.groupBox_2)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(10, 60, 54, 16))
        self.fangxiang1 = QComboBox(self.groupBox_2)
        self.fangxiang1.addItem("")
        self.fangxiang1.addItem("")
        self.fangxiang1.addItem("")
        self.fangxiang1.setObjectName(u"fangxiang1")
        self.fangxiang1.setGeometry(QRect(70, 30, 81, 22))
        self.label_9 = QLabel(self.groupBox_2)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(10, 90, 54, 16))
        self.jiasudu1 = QDoubleSpinBox(self.groupBox_2)
        self.jiasudu1.setObjectName(u"jiasudu1")
        self.jiasudu1.setGeometry(QRect(70, 90, 81, 21))
        self.jiasudu1.setMaximum(1000.000000000000000)
        self.label_10 = QLabel(self.groupBox_2)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(10, 120, 54, 16))
        self.xianshijiaodu1 = QLabel(self.groupBox_2)
        self.xianshijiaodu1.setObjectName(u"xianshijiaodu1")
        self.xianshijiaodu1.setGeometry(QRect(10, 150, 141, 31))
        self.jiaodu1 = QDoubleSpinBox(self.groupBox_2)
        self.jiaodu1.setObjectName(u"jiaodu1")
        self.jiaodu1.setGeometry(QRect(70, 120, 81, 21))
        self.jiaodu1.setMinimum(-360.000000000000000)
        self.jiaodu1.setMaximum(360.000000000000000)
        self.kaishi = QPushButton(super_student_clap)
        self.kaishi.setObjectName(u"kaishi")
        self.kaishi.setGeometry(QRect(1130, 10, 151, 81))
        font2 = QFont()
        font2.setPointSize(26)
        font2.setBold(True)
        self.kaishi.setFont(font2)
        self.stop = QPushButton(super_student_clap)
        self.stop.setObjectName(u"stop")
        self.stop.setGeometry(QRect(1130, 100, 151, 81))
        self.stop.setFont(font2)
        self.groupBox_4 = QGroupBox(super_student_clap)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(390, 0, 161, 181))
        self.groupBox_4.setFont(font1)
        self.label_15 = QLabel(self.groupBox_4)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(10, 30, 51, 21))
        self.sudu3 = QDoubleSpinBox(self.groupBox_4)
        self.sudu3.setObjectName(u"sudu3")
        self.sudu3.setGeometry(QRect(70, 60, 81, 21))
        self.sudu3.setMaximum(10000.000000000000000)
        self.label_16 = QLabel(self.groupBox_4)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(10, 60, 54, 16))
        self.fangxiang3 = QComboBox(self.groupBox_4)
        self.fangxiang3.addItem("")
        self.fangxiang3.addItem("")
        self.fangxiang3.addItem("")
        self.fangxiang3.setObjectName(u"fangxiang3")
        self.fangxiang3.setGeometry(QRect(70, 30, 81, 22))
        self.label_17 = QLabel(self.groupBox_4)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(10, 90, 54, 16))
        self.jiasudu3 = QDoubleSpinBox(self.groupBox_4)
        self.jiasudu3.setObjectName(u"jiasudu3")
        self.jiasudu3.setGeometry(QRect(70, 90, 81, 21))
        self.jiasudu3.setMaximum(1000.000000000000000)
        self.label_18 = QLabel(self.groupBox_4)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(10, 120, 54, 16))
        self.jiaodu3 = QDoubleSpinBox(self.groupBox_4)
        self.jiaodu3.setObjectName(u"jiaodu3")
        self.jiaodu3.setGeometry(QRect(70, 120, 81, 21))
        self.jiaodu3.setMinimum(-360.000000000000000)
        self.jiaodu3.setMaximum(360.000000000000000)
        self.xianshijiaodu3 = QLabel(self.groupBox_4)
        self.xianshijiaodu3.setObjectName(u"xianshijiaodu3")
        self.xianshijiaodu3.setGeometry(QRect(10, 150, 141, 31))
        self.groupBox_5 = QGroupBox(super_student_clap)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setGeometry(QRect(580, 0, 161, 181))
        self.groupBox_5.setFont(font1)
        self.label_19 = QLabel(self.groupBox_5)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(10, 30, 51, 21))
        self.sudu4 = QDoubleSpinBox(self.groupBox_5)
        self.sudu4.setObjectName(u"sudu4")
        self.sudu4.setGeometry(QRect(70, 60, 81, 21))
        self.sudu4.setMaximum(10000.000000000000000)
        self.label_20 = QLabel(self.groupBox_5)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(10, 60, 54, 16))
        self.fangxiang4 = QComboBox(self.groupBox_5)
        self.fangxiang4.addItem("")
        self.fangxiang4.addItem("")
        self.fangxiang4.addItem("")
        self.fangxiang4.setObjectName(u"fangxiang4")
        self.fangxiang4.setGeometry(QRect(70, 30, 81, 22))
        self.label_21 = QLabel(self.groupBox_5)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(10, 90, 54, 16))
        self.jiasudu4 = QDoubleSpinBox(self.groupBox_5)
        self.jiasudu4.setObjectName(u"jiasudu4")
        self.jiasudu4.setGeometry(QRect(70, 90, 81, 21))
        self.jiasudu4.setMaximum(1000.000000000000000)
        self.label_22 = QLabel(self.groupBox_5)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(10, 120, 54, 16))
        self.jiaodu4 = QDoubleSpinBox(self.groupBox_5)
        self.jiaodu4.setObjectName(u"jiaodu4")
        self.jiaodu4.setGeometry(QRect(70, 120, 81, 21))
        self.jiaodu4.setMinimum(-360.000000000000000)
        self.jiaodu4.setMaximum(360.000000000000000)
        self.xianshijiaodu4 = QLabel(self.groupBox_5)
        self.xianshijiaodu4.setObjectName(u"xianshijiaodu4")
        self.xianshijiaodu4.setGeometry(QRect(10, 150, 141, 31))
        self.groupBox_6 = QGroupBox(super_student_clap)
        self.groupBox_6.setObjectName(u"groupBox_6")
        self.groupBox_6.setGeometry(QRect(770, 0, 161, 181))
        self.groupBox_6.setFont(font1)
        self.label_23 = QLabel(self.groupBox_6)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(10, 30, 51, 21))
        self.sudu5 = QDoubleSpinBox(self.groupBox_6)
        self.sudu5.setObjectName(u"sudu5")
        self.sudu5.setGeometry(QRect(70, 60, 81, 21))
        self.sudu5.setMaximum(10000.000000000000000)
        self.label_24 = QLabel(self.groupBox_6)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(10, 60, 54, 16))
        self.fangxiang5 = QComboBox(self.groupBox_6)
        self.fangxiang5.addItem("")
        self.fangxiang5.addItem("")
        self.fangxiang5.addItem("")
        self.fangxiang5.setObjectName(u"fangxiang5")
        self.fangxiang5.setGeometry(QRect(70, 30, 81, 22))
        self.label_25 = QLabel(self.groupBox_6)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(10, 90, 54, 16))
        self.jiasudu5 = QDoubleSpinBox(self.groupBox_6)
        self.jiasudu5.setObjectName(u"jiasudu5")
        self.jiasudu5.setGeometry(QRect(70, 90, 81, 21))
        self.jiasudu5.setMaximum(1000.000000000000000)
        self.label_26 = QLabel(self.groupBox_6)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(10, 120, 54, 16))
        self.jiaodu5 = QDoubleSpinBox(self.groupBox_6)
        self.jiaodu5.setObjectName(u"jiaodu5")
        self.jiaodu5.setGeometry(QRect(70, 120, 81, 21))
        self.jiaodu5.setMinimum(-360.000000000000000)
        self.jiaodu5.setMaximum(360.000000000000000)
        self.xianshijiaodu5 = QLabel(self.groupBox_6)
        self.xianshijiaodu5.setObjectName(u"xianshijiaodu5")
        self.xianshijiaodu5.setGeometry(QRect(10, 150, 141, 31))
        self.groupBox_7 = QGroupBox(super_student_clap)
        self.groupBox_7.setObjectName(u"groupBox_7")
        self.groupBox_7.setGeometry(QRect(960, 0, 161, 181))
        self.groupBox_7.setFont(font1)
        self.label_27 = QLabel(self.groupBox_7)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(10, 30, 51, 21))
        self.sudu6 = QDoubleSpinBox(self.groupBox_7)
        self.sudu6.setObjectName(u"sudu6")
        self.sudu6.setGeometry(QRect(70, 60, 81, 21))
        self.sudu6.setMaximum(10000.000000000000000)
        self.label_28 = QLabel(self.groupBox_7)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(10, 60, 54, 16))
        self.fangxiang6 = QComboBox(self.groupBox_7)
        self.fangxiang6.addItem("")
        self.fangxiang6.addItem("")
        self.fangxiang6.addItem("")
        self.fangxiang6.setObjectName(u"fangxiang6")
        self.fangxiang6.setGeometry(QRect(70, 30, 81, 22))
        self.label_29 = QLabel(self.groupBox_7)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(10, 90, 54, 16))
        self.jiasudu6 = QDoubleSpinBox(self.groupBox_7)
        self.jiasudu6.setObjectName(u"jiasudu6")
        self.jiasudu6.setGeometry(QRect(70, 90, 81, 21))
        self.jiasudu6.setMaximum(1000.000000000000000)
        self.label_30 = QLabel(self.groupBox_7)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(10, 120, 54, 16))
        self.jiaodu6 = QDoubleSpinBox(self.groupBox_7)
        self.jiaodu6.setObjectName(u"jiaodu6")
        self.jiaodu6.setGeometry(QRect(70, 120, 81, 21))
        self.jiaodu6.setMinimum(-360.000000000000000)
        self.jiaodu6.setMaximum(360.000000000000000)
        self.xianshijiaodu6 = QLabel(self.groupBox_7)
        self.xianshijiaodu6.setObjectName(u"xianshijiaodu6")
        self.xianshijiaodu6.setGeometry(QRect(10, 150, 141, 31))
        self.groupBox_3 = QGroupBox(super_student_clap)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(200, 0, 161, 181))
        self.groupBox_3.setFont(font1)
        self.label_11 = QLabel(self.groupBox_3)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(10, 30, 51, 21))
        self.sudu2 = QDoubleSpinBox(self.groupBox_3)
        self.sudu2.setObjectName(u"sudu2")
        self.sudu2.setGeometry(QRect(70, 60, 81, 21))
        self.sudu2.setMaximum(10000.000000000000000)
        self.label_12 = QLabel(self.groupBox_3)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(10, 60, 54, 16))
        self.fangxiang2 = QComboBox(self.groupBox_3)
        self.fangxiang2.addItem("")
        self.fangxiang2.addItem("")
        self.fangxiang2.addItem("")
        self.fangxiang2.setObjectName(u"fangxiang2")
        self.fangxiang2.setGeometry(QRect(70, 30, 81, 22))
        self.label_13 = QLabel(self.groupBox_3)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(10, 90, 54, 16))
        self.jiasudu2 = QDoubleSpinBox(self.groupBox_3)
        self.jiasudu2.setObjectName(u"jiasudu2")
        self.jiasudu2.setGeometry(QRect(70, 90, 81, 21))
        self.jiasudu2.setMaximum(1000.000000000000000)
        self.label_14 = QLabel(self.groupBox_3)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(10, 120, 54, 16))
        self.jiaodu2 = QDoubleSpinBox(self.groupBox_3)
        self.jiaodu2.setObjectName(u"jiaodu2")
        self.jiaodu2.setGeometry(QRect(70, 120, 81, 21))
        self.jiaodu2.setMinimum(-360.000000000000000)
        self.jiaodu2.setMaximum(360.000000000000000)
        self.xianshijiaodu2 = QLabel(self.groupBox_3)
        self.xianshijiaodu2.setObjectName(u"xianshijiaodu2")
        self.xianshijiaodu2.setGeometry(QRect(10, 150, 141, 31))
        self.huiling = QPushButton(super_student_clap)
        self.huiling.setObjectName(u"huiling")
        self.huiling.setGeometry(QRect(10, 240, 101, 81))
        font3 = QFont()
        font3.setPointSize(20)
        font3.setBold(False)
        self.huiling.setFont(font3)

        self.retranslateUi(super_student_clap)

        QMetaObject.connectSlotsByName(super_student_clap)
    # setupUi

    def retranslateUi(self, super_student_clap):
        super_student_clap.setWindowTitle(QCoreApplication.translate("super_student_clap", u"Form", None))
        self.groupBox.setTitle(QCoreApplication.translate("super_student_clap", u"\u4e32\u53e3\u8fde\u63a5\u533a", None))
        self.label.setText(QCoreApplication.translate("super_student_clap", u"\u4e32\u53e3\uff1a", None))
        self.label_2.setText(QCoreApplication.translate("super_student_clap", u"\u6ce2\u7279\u7387\uff1a", None))
        self.label_3.setText(QCoreApplication.translate("super_student_clap", u"\u7535\u673a\u6570\uff1a", None))
        self.dakaichuankou.setText(QCoreApplication.translate("super_student_clap", u"\u6253\u5f00\u4e32\u53e3", None))
        self.guanbichuankou.setText(QCoreApplication.translate("super_student_clap", u"\u5173\u95ed\u4e32\u53e3", None))
        self.botelv.setItemText(0, QCoreApplication.translate("super_student_clap", u"19200", None))
        self.botelv.setItemText(1, QCoreApplication.translate("super_student_clap", u"9600", None))
        self.botelv.setItemText(2, QCoreApplication.translate("super_student_clap", u"25000", None))
        self.botelv.setItemText(3, QCoreApplication.translate("super_student_clap", u"38400", None))
        self.botelv.setItemText(4, QCoreApplication.translate("super_student_clap", u"57600", None))
        self.botelv.setItemText(5, QCoreApplication.translate("super_student_clap", u"115200", None))
        self.botelv.setItemText(6, QCoreApplication.translate("super_student_clap", u"256000", None))
        self.botelv.setItemText(7, QCoreApplication.translate("super_student_clap", u"512000", None))
        self.botelv.setItemText(8, QCoreApplication.translate("super_student_clap", u"921600", None))

        self.chuankou.setItemText(0, QCoreApplication.translate("super_student_clap", u"COM5", None))

        self.dianjishu.setItemText(0, QCoreApplication.translate("super_student_clap", u"1", None))
        self.dianjishu.setItemText(1, QCoreApplication.translate("super_student_clap", u"2", None))
        self.dianjishu.setItemText(2, QCoreApplication.translate("super_student_clap", u"3", None))
        self.dianjishu.setItemText(3, QCoreApplication.translate("super_student_clap", u"4", None))
        self.dianjishu.setItemText(4, QCoreApplication.translate("super_student_clap", u"5", None))
        self.dianjishu.setItemText(5, QCoreApplication.translate("super_student_clap", u"6", None))

        self.groupBox_2.setTitle(QCoreApplication.translate("super_student_clap", u"\u7535\u673a1", None))
        self.label_7.setText(QCoreApplication.translate("super_student_clap", u"\u65b9\u5411\uff1a", None))
        self.label_8.setText(QCoreApplication.translate("super_student_clap", u"\u901f\u5ea6\uff1a", None))
        self.fangxiang1.setItemText(0, QCoreApplication.translate("super_student_clap", u"\u9006\u89e3", None))
        self.fangxiang1.setItemText(1, QCoreApplication.translate("super_student_clap", u"CW", None))
        self.fangxiang1.setItemText(2, QCoreApplication.translate("super_student_clap", u"CCW", None))

        self.label_9.setText(QCoreApplication.translate("super_student_clap", u"\u52a0\u901f\u5ea6\uff1a", None))
        self.label_10.setText(QCoreApplication.translate("super_student_clap", u"\u89d2\u5ea6\uff1a", None))
        self.xianshijiaodu1.setText("")
        self.kaishi.setText(QCoreApplication.translate("super_student_clap", u"\u5f00\u59cb\u5de5\u4f5c", None))
        self.stop.setText(QCoreApplication.translate("super_student_clap", u"\u505c\u6b62\u5de5\u4f5c", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("super_student_clap", u"\u7535\u673a3", None))
        self.label_15.setText(QCoreApplication.translate("super_student_clap", u"\u65b9\u5411\uff1a", None))
        self.label_16.setText(QCoreApplication.translate("super_student_clap", u"\u901f\u5ea6\uff1a", None))
        self.fangxiang3.setItemText(0, QCoreApplication.translate("super_student_clap", u"\u9006\u89e3", None))
        self.fangxiang3.setItemText(1, QCoreApplication.translate("super_student_clap", u"CW", None))
        self.fangxiang3.setItemText(2, QCoreApplication.translate("super_student_clap", u"CCW", None))

        self.label_17.setText(QCoreApplication.translate("super_student_clap", u"\u52a0\u901f\u5ea6\uff1a", None))
        self.label_18.setText(QCoreApplication.translate("super_student_clap", u"\u89d2\u5ea6\uff1a", None))
        self.xianshijiaodu3.setText("")
        self.groupBox_5.setTitle(QCoreApplication.translate("super_student_clap", u"\u7535\u673a4", None))
        self.label_19.setText(QCoreApplication.translate("super_student_clap", u"\u65b9\u5411\uff1a", None))
        self.label_20.setText(QCoreApplication.translate("super_student_clap", u"\u901f\u5ea6\uff1a", None))
        self.fangxiang4.setItemText(0, QCoreApplication.translate("super_student_clap", u"\u9006\u89e3", None))
        self.fangxiang4.setItemText(1, QCoreApplication.translate("super_student_clap", u"CW", None))
        self.fangxiang4.setItemText(2, QCoreApplication.translate("super_student_clap", u"CCW", None))

        self.label_21.setText(QCoreApplication.translate("super_student_clap", u"\u52a0\u901f\u5ea6\uff1a", None))
        self.label_22.setText(QCoreApplication.translate("super_student_clap", u"\u89d2\u5ea6\uff1a", None))
        self.xianshijiaodu4.setText("")
        self.groupBox_6.setTitle(QCoreApplication.translate("super_student_clap", u"\u7535\u673a5", None))
        self.label_23.setText(QCoreApplication.translate("super_student_clap", u"\u65b9\u5411\uff1a", None))
        self.label_24.setText(QCoreApplication.translate("super_student_clap", u"\u901f\u5ea6\uff1a", None))
        self.fangxiang5.setItemText(0, QCoreApplication.translate("super_student_clap", u"\u9006\u89e3", None))
        self.fangxiang5.setItemText(1, QCoreApplication.translate("super_student_clap", u"CW", None))
        self.fangxiang5.setItemText(2, QCoreApplication.translate("super_student_clap", u"CCW", None))

        self.label_25.setText(QCoreApplication.translate("super_student_clap", u"\u52a0\u901f\u5ea6\uff1a", None))
        self.label_26.setText(QCoreApplication.translate("super_student_clap", u"\u89d2\u5ea6\uff1a", None))
        self.xianshijiaodu5.setText("")
        self.groupBox_7.setTitle(QCoreApplication.translate("super_student_clap", u"\u7535\u673a6", None))
        self.label_27.setText(QCoreApplication.translate("super_student_clap", u"\u65b9\u5411\uff1a", None))
        self.label_28.setText(QCoreApplication.translate("super_student_clap", u"\u901f\u5ea6\uff1a", None))
        self.fangxiang6.setItemText(0, QCoreApplication.translate("super_student_clap", u"\u9006\u89e3", None))
        self.fangxiang6.setItemText(1, QCoreApplication.translate("super_student_clap", u"CW", None))
        self.fangxiang6.setItemText(2, QCoreApplication.translate("super_student_clap", u"CCW", None))

        self.label_29.setText(QCoreApplication.translate("super_student_clap", u"\u52a0\u901f\u5ea6\uff1a", None))
        self.label_30.setText(QCoreApplication.translate("super_student_clap", u"\u89d2\u5ea6\uff1a", None))
        self.xianshijiaodu6.setText("")
        self.groupBox_3.setTitle(QCoreApplication.translate("super_student_clap", u"\u7535\u673a2", None))
        self.label_11.setText(QCoreApplication.translate("super_student_clap", u"\u65b9\u5411\uff1a", None))
        self.label_12.setText(QCoreApplication.translate("super_student_clap", u"\u901f\u5ea6\uff1a", None))
        self.fangxiang2.setItemText(0, QCoreApplication.translate("super_student_clap", u"\u9006\u89e3", None))
        self.fangxiang2.setItemText(1, QCoreApplication.translate("super_student_clap", u"CW", None))
        self.fangxiang2.setItemText(2, QCoreApplication.translate("super_student_clap", u"CCW", None))

        self.label_13.setText(QCoreApplication.translate("super_student_clap", u"\u52a0\u901f\u5ea6\uff1a", None))
        self.label_14.setText(QCoreApplication.translate("super_student_clap", u"\u89d2\u5ea6\uff1a", None))
        self.xianshijiaodu2.setText("")
        self.huiling.setText(QCoreApplication.translate("super_student_clap", u"\u56de\u96f6", None))
    # retranslateUi

